package com.example.demo.models;

import javax.persistence.*;

@Entity
@Table(name = "Person")
public class Person {

    @Id
    @Column(name = "id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    @Column(name = "username")
    private String username;

    @Column(name = "year_of_birth")
    private int yeaOfBirth;

    @Column(name = "password")
    private String password;

    public Person(){}

    public Person(String username, int yeaOfBirth, String password) {
        this.username = username;
        this.yeaOfBirth = yeaOfBirth;
        this.password = password;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public int getYeaOfBirth() {
        return yeaOfBirth;
    }

    public void setYeaOfBirth(int yeaOfBirth) {
        this.yeaOfBirth = yeaOfBirth;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public String toString() {
        return "Person{" +
                "id=" + id +
                ", username='" + username + '\'' +
                ", yeaOfBirth=" + yeaOfBirth +
                ", password='" + password + '\'' +
                '}';
    }
}
/*
create table person(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username varchar(100) NOT NULL,
    year_of_birth int NOT NULL,
    password varchar NOT NULL
)
 */